
import = [
   "~/.config/alacritty/catppuccin-frappe.toml"
  ]

[env]
term = "xterm-256color"

[font]
size = 15.0
offset.y = 3

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.95
padding={x=5, y=5}
